[package]
name = "crowdfunding"
version = "0.0.1"
authors = [ "you",]
edition = "2018"

[lib]
path = "src/crowdfunding_main.rs"

[dependencies.multiversx-sc]
version = "0.39.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.0"
